"""Discovery stage registry for self-improvement inspection."""

from __future__ import annotations

from qa_z.self_improvement_stage_groups import (
    BASELINE_DISCOVERY_STAGES,
    EXECUTION_CONTRACT_DISCOVERY_STAGES,
    EXECUTION_DISCOVERY_STAGES,
    LOOP_HEALTH_DISCOVERY_STAGES,
    SURFACE_DISCOVERY_STAGES,
    WORKTREE_DISCOVERY_STAGES,
)

__all__ = [
    "DISCOVERY_PIPELINE_STAGES",
    "DISCOVERY_STAGE_NAMES",
]

DISCOVERY_PIPELINE_STAGES = [
    *BASELINE_DISCOVERY_STAGES,
    *EXECUTION_DISCOVERY_STAGES,
    *SURFACE_DISCOVERY_STAGES,
    *EXECUTION_CONTRACT_DISCOVERY_STAGES,
    *WORKTREE_DISCOVERY_STAGES,
    *LOOP_HEALTH_DISCOVERY_STAGES,
]

DISCOVERY_STAGE_NAMES = tuple(stage.name for stage in DISCOVERY_PIPELINE_STAGES)
